export enum Aminos {
    ALA = '../assets/graphIcons/ALA.png',
    ARG = '../assets/graphIcons/ARG.png',
    ASN = '../assets/graphIcons/ASN.png',
    ASP = '../assets/graphIcons/ASP.png',
    CYS = '../assets/graphIcons/CYS.png',
    GLN = '../assets/graphIcons/GLN.png',
    GLU = '../assets/graphIcons/GLU.png',
    GLY = '../assets/graphIcons/GLY.png',
    HIS = '../assets/graphIcons/HIS.png',
    ILE = '../assets/graphIcons/ILE.png',
    LEU = '../assets/graphIcons/LEU.png',
    LYS = '../assets/graphIcons/LYS.png',
    MET = '../assets/graphIcons/MET.png',
    PHE = '../assets/graphIcons/PHE.png',
    PRO = '../assets/graphIcons/PRO.png',
    SER = '../assets/graphIcons/SER.png',
    THR = '../assets/graphIcons/THR.png',
    TRP = '../assets/graphIcons/TRP.png',
    TYR = '../assets/graphIcons/TYR.png',
    VAL = '../assets/graphIcons/VAL.png',
    ANY = '../assets/graphIcons/ANY.png'
}